// Longest plausible stay at the school, used by the signup wizard
// (Auth.jsx) and the social-login catch-up form (FinishSignup.jsx) to
// sanity-check the "from" and "to" year dropdowns against each other.
// Generous on purpose — prep years, a repeated grade or two, is real;
// twenty years is a mis-picked decade in one of the two dropdowns, which
// the committee otherwise has to catch by hand when verifying against
// school records.
export const MAX_SCHOOL_YEARS = 12

// Grouped from real alumni occupation data.
// "Other" is handled separately in the UI (shows a text input).
//
// Every label here is also a stored value on profiles.industry and jobs.industry,
// so labels are append-only — renaming one silently demotes every profile using
// it to "Other" (see the INDUSTRIES.includes check in Profile.jsx). Add new
// entries at the end of the relevant block instead.
//
// The list is deliberately long: nobody scrolls it, they type. INDUSTRY_KEYWORDS
// below is what makes the long tail findable, so a new entry should almost
// always come with keywords.
export const INDUSTRIES = [
  'Accounting & Finance',
  'Agriculture & Wine',
  'Architecture & Design',
  'Civil Engineering',
  'Software Engineering & Development',
  'Mechanical/Manufacturing Engineering',
  'Other Engineering (electrical, chemical, marine, etc.)',
  'Banking & Financial Services',
  'Insurance & Actuarial Science',
  'Investment & Asset Management',
  'Construction & Project Management',
  'Property & Real Estate',
  'Legal',
  'Consulting',
  'Management & Operations',
  'Human Resources & Recruitment',
  'Marketing & Advertising',
  'Media & Creative (publishing, film, design)',
  'Public Relations & Communications',
  'Education & Academia',
  'Research & Development',
  'Healthcare & Medical',
  'Pharmaceuticals & Biotech',
  'Mental Health & Psychology',
  'Energy & Environment',
  'Mining & Resources',
  'Manufacturing & Industrial',
  'Hospitality & Tourism',
  'Food & Beverage',
  'Retail & Wholesale',
  'E-commerce',
  'Transport & Logistics',
  'Telecommunications',
  'Utilities & Water',
  'Government & Public Sector',
  'Non-profit & NGO',
  'Sport & Recreation',
  'Arts & Entertainment',
  'Military & Defence',
  // --- Tech split out from "Software Engineering & Development", which alumni
  // in IT support, networks, data or security kept skipping over. ---
  'Information Technology & IT Services',
  'Data, Analytics & AI',
  'Cybersecurity & Information Security',
  'Gaming & Esports',
  // --- Commercial roles that previously had nowhere to sit. ---
  'Sales & Business Development',
  'Procurement & Supply Chain',
  'Customer Service & Call Centres',
  'Administration & Office Support',
  'Entrepreneurship & Startups',
  'Events & Conference Management',
  // --- Creative, split from the broad "Media & Creative". ---
  'Design (Graphic, UX & Product)',
  'Photography & Videography',
  'Fashion, Apparel & Textiles',
  'Printing & Packaging',
  // --- Transport & heavy industry. ---
  'Aviation & Aerospace',
  'Automotive',
  'Maritime & Shipping',
  // --- Trades and services: a large slice of the alumni base was being
  // pushed into "Other" here. ---
  'Skilled Trades (plumbing, electrical, carpentry)',
  'Facilities Management & Cleaning',
  'Security Services & Risk',
  'Emergency Services (police, fire, paramedic)',
  'Waste Management & Recycling',
  'Beauty, Wellness & Personal Care',
  'Funeral Services',
  // --- Land & animals. ---
  'Veterinary & Animal Care',
  'Forestry & Fishing',
  // --- People-facing / community. ---
  'Religion & Ministry',
  'Social Work & Community Development',
  'Childcare & Early Childhood Development',
  'Translation, Language & Localisation',
  // --- Not currently in an industry. Kept last so they never crowd out real
  // matches when the box is empty. ---
  'Between roles',
  'Homemaker & Caregiver',
  'Retired',
  'Student',
]

// Hidden search terms per industry, so the box matches how people actually
// describe themselves rather than the label we happened to pick. Typing
// "dokter", "coder", "prokureur" or "plumber" all land on the right row —
// none of those words appear in any label.
//
// Afrikaans terms are in on purpose: SACS is a Cape Town school with a good
// number of Afrikaans-speaking alumni who will reach for "boer" or
// "onderwyser" first.
// Matching is substring-based, so short stems ("boer") also cover the longer
// forms ("boerdery"). Keep entries lowercase.
export const INDUSTRY_KEYWORDS = {
  'Accounting & Finance': 'accountant rekenmeester bookkeeper boekhouer ca(sa) tax belasting audit ouditeur payroll cfo financial controller',
  'Agriculture & Wine': 'farmer boer boerdery farming plaas wine wyn wynmaker winemaker viticulture vineyard wingerd crop livestock vee agri agriculture landbou horticulture irrigation',
  'Architecture & Design': 'architect argitek town planner urban planning interior designer landscape draughtsman tekenaar bim revit',
  'Civil Engineering': 'civil engineer ingenieur structural geotechnical roads water sanitation surveyor landmeter quantity surveyor bouingenieur infrastructure',
  'Software Engineering & Development': 'software developer dev coder coding programmer programmeur engineer frontend backend full stack fullstack web app mobile devops cloud api java python javascript react .net php ruby golang',
  'Mechanical/Manufacturing Engineering': 'mechanical engineer meganiese ingenieur manufacturing production plant cad automation robotics maintenance millwright hvac tooling machining lean six sigma',
  'Other Engineering (electrical, chemical, marine, etc.)': 'electrical engineer elektriese chemical chemiese industrial metallurgical marine mining engineer petroleum process engineer nuclear biomedical engineering ingenieur',
  'Banking & Financial Services': 'bank banker banking credit lending mortgage bond originator fintech payments retail banking relationship manager treasury',
  'Insurance & Actuarial Science': 'insurance versekering actuary aktuaris broker makelaar underwriter claims risk short term life insurance reinsurance',
  'Investment & Asset Management': 'investment invest asset management fund manager portfolio wealth private equity venture capital vc hedge fund analyst stockbroker trader equities financial advisor finansiele adviseur',
  'Construction & Project Management': 'construction bou builder bouer contractor kontrakteur site manager project manager quantity surveyor bouprojek civils foreman',
  'Property & Real Estate': 'property eiendom real estate estate agent eiendomsagent letting rental landlord valuer waardeerder facilities developer body corporate managing agent',
  'Legal': 'lawyer prokureur attorney advocate advokaat legal law regsgeleerde conveyancer aktebesorger notary paralegal compliance litigation candidate attorney judge magistrate regter',
  'Consulting': 'consultant konsultant consulting advisory strategy management consultant business analyst',
  'Management & Operations': 'manager bestuurder operations ops general manager gm coo executive director owner md managing director business owner supervisor',
  'Human Resources & Recruitment': 'hr human resources menslike hulpbronne recruiter recruitment talent acquisition headhunter people culture ir industrial relations training development remuneration',
  'Marketing & Advertising': 'marketing bemarking advertising advertensie brand digital marketing seo social media content marketing campaign copywriter media buyer',
  'Media & Creative (publishing, film, design)': 'media journalist joernalis editor redakteur publishing publisher film tv television producer director writer author skrywer creative broadcast radio podcast animation',
  'Public Relations & Communications': 'pr public relations communications kommunikasie corporate comms spokesperson media relations internal communications reputation',
  'Education & Academia': 'teacher onderwyser onderwys education educator lecturer dosent professor academic university school principal skoolhoof tutor researcher academia phd postgrad librarian',
  'Research & Development': 'research researcher navorsing r&d scientist wetenskaplike laboratory lab innovation product research clinical research',
  'Healthcare & Medical': 'doctor dokter medical medies gp physician surgeon chirurg specialist nurse verpleegster verpleegkundige dentist tandarts dental physio physiotherapist fisioterapeut occupational therapist radiographer paramedic optometrist chiropractor dietitian dieetkundige speech therapist healthcare hospital clinic',
  'Pharmaceuticals & Biotech': 'pharmacist apteker pharmacy apteek pharmaceutical pharma biotech biotechnology medical rep clinical trials regulatory affairs drug',
  'Mental Health & Psychology': 'psychologist sielkundige psychology sielkunde therapist terapeut counsellor berader psychiatrist psigiater mental health social counselling coach',
  'Energy & Environment': 'energy energie environment omgewing environmental renewable solar sonkrag wind power eskom sustainability climate conservation bewaring carbon esg green',
  'Mining & Resources': 'mining myn mine mynbou geologist geoloog minerals resources exploration drilling coal gold platinum quarry metallurgy',
  'Manufacturing & Industrial': 'manufacturing vervaardiging factory fabriek industrial production plant assembly fmcg packaging line supervisor operations',
  'Hospitality & Tourism': 'hospitality gasvryheid hotel guesthouse gastehuis lodge tourism toerisme travel agent tour guide safari restaurant manager casino resort b&b airbnb host',
  'Food & Beverage': 'food kos beverage drank chef kok restaurant catering spys bakery bakker butcher slagter brewing brewery brouery barista coffee food science nutrition',
  'Retail & Wholesale': 'retail kleinhandel shop winkel store manager wholesale groothandel merchandiser buyer fmcg supermarket franchise till cashier',
  'E-commerce': 'ecommerce e-commerce online store online shop takealot shopify marketplace dropshipping online retail',
  'Transport & Logistics': 'transport logistics logistiek freight vragte shipping courier trucking truck driver vervoer warehouse pakhuis distribution fleet delivery customs clearing forwarding',
  'Telecommunications': 'telecoms telecommunications telekommunikasie network networks fibre fiber isp mobile operator vodacom mtn telkom rf satellite',
  'Utilities & Water': 'utilities water munisipaliteit municipal electricity elektrisiteit power grid sanitation waste water reticulation eskom substation',
  'Government & Public Sector': 'government regering public sector staatsdiens municipality munisipaliteit civil servant policy beleid politics politiek politician diplomat foreign affairs department state parliament dha sars',
  'Non-profit & NGO': 'nonprofit non-profit ngo npo charity liefdadigheid foundation stigting fundraising donor volunteer development aid humanitarian outreach',
  'Sport & Recreation': 'sport sports coach afrigter rugby cricket krieket athlete fitness gym personal trainer biokineticist biokinetikus recreation sport science physio sport management',
  'Arts & Entertainment': 'art kuns artist kunstenaar musician musikant music musiek band singer actor akteur theatre teater dance performing arts gallery museum curator entertainment dj',
  'Military & Defence': 'military weermag defence sandf army navy vloot air force lugmag soldier soldaat officer veteran armaments denel',
  'Information Technology & IT Services': 'it information technology tegnologie support helpdesk desktop support sysadmin system administrator network administrator infrastructure server hardware msp technician rekenaar computers erp sap salesforce crm implementation',
  'Data, Analytics & AI': 'data analyst data scientist analytics ontleding business intelligence bi power bi tableau sql machine learning ml ai artificial intelligence data engineer statistics statistiek reporting big data',
  'Cybersecurity & Information Security': 'cyber cybersecurity infosec information security security analyst penetration testing pen test soc grc iso27001 popia compliance security ethical hacking',
  'Gaming & Esports': 'gaming games game development game dev esports unity unreal game designer streamer twitch',
  'Sales & Business Development': 'sales verkope sales rep representative account manager account executive business development bd key accounts new business territory manager telesales field sales commission quota',
  'Procurement & Supply Chain': 'procurement verkryging purchasing inkope buyer supply chain sourcing vendor supplier contracts tenders tender inventory stock control demand planning',
  'Customer Service & Call Centres': 'customer service client service kliëntediens klientediens call centre call center contact centre bpo support agent customer success account support helpdesk',
  'Administration & Office Support': 'admin administration administrasie administrator office manager kantoor secretary sekretaresse pa personal assistant executive assistant receptionist ontvangsdame data capturer clerk klerk',
  'Entrepreneurship & Startups': 'entrepreneur entrepreneurship ondernemer startup start-up founder stigter co-founder self employed selfemployed freelance freelancer own business eie besigheid small business smme side hustle',
  'Events & Conference Management': 'events event management conference konferensie wedding troue planner exhibitions expo venue functions coordinator catering events production av',
  'Design (Graphic, UX & Product)': 'design designer ontwerper graphic design grafiese ux ui user experience product design web design branding identity illustrator illustrator photoshop figma typography motion graphics',
  'Photography & Videography': 'photographer fotograaf photography fotografie videographer video film maker wedding photographer editing drone cinematography studio',
  'Fashion, Apparel & Textiles': 'fashion mode clothing klere apparel textile tekstiel garment seamstress naaldwerk tailor kleremaker boutique retail fashion stylist design merchandising',
  'Printing & Packaging': 'printing drukkery printer print signage packaging verpakking labels litho digital printing screen printing bindery',
  'Aviation & Aerospace': 'aviation lugvaart pilot vlieënier vlieenier aircraft aeroplane airline lugredery cabin crew air traffic control atc aerospace avionics aircraft maintenance ame airport flight',
  'Automotive': 'automotive motor cars motorvoertuie vehicle dealership dealer mechanic werktuigkundige panel beater workshop parts motor industry fleet auto electrician car sales',
  'Maritime & Shipping': 'maritime maritiem shipping ships skip vessel harbour hawe port seafarer sailor merchant navy fishing vessel marine ship yacht stevedore transnet',
  'Skilled Trades (plumbing, electrical, carpentry)': 'trades tradesman artisan ambagsman plumber loodgieter electrician elektrisiën elektrisien carpenter skrynwerker joiner welder sweiser boilermaker fitter turner mechanic painter tiler plasterer bricklayer messelaar handyman roofer hvac technician apprentice',
  'Facilities Management & Cleaning': 'facilities facility management cleaning skoonmaak janitorial hygiene pest control landscaping tuindienste gardening maintenance building management caretaker',
  'Security Services & Risk': 'security sekuriteit guard wagte armed response alarm cctv access control risk management loss prevention investigations investigator private security fidelity adt',
  'Emergency Services (police, fire, paramedic)': 'police polisie saps officer detective speurder fire brandweer firefighter brandbestryder paramedic ambulance ems emergency rescue disaster management traffic verkeer metro',
  'Waste Management & Recycling': 'waste afval recycling herwinning refuse rubbish landfill scrap skips hazardous waste circular economy',
  'Beauty, Wellness & Personal Care': 'beauty skoonheid salon hairdresser haarkapper barber hair stylist nails nagels beautician skincare spa massage therapist masseur aesthetics cosmetics wellness',
  'Funeral Services': 'funeral begrafnis undertaker begrafnisondernemer mortuary crematorium burial memorial funeral parlour',
  'Veterinary & Animal Care': 'vet veterinarian veearts veterinary animal diere animal care pet troeteldier kennels grooming groomer animal welfare spca wildlife wild game ranger boskap zoo equine horses perde',
  'Forestry & Fishing': 'forestry bosbou timber hout plantation sawmill saagmeul logging fishing visserye fisheries aquaculture akwakultuur abalone hake trawler',
  'Religion & Ministry': 'church kerk ministry bediening pastor predikant dominee minister priest reverend missionary sendeling chaplain kapelaan theology teologie youth pastor worship religious',
  'Social Work & Community Development': 'social work maatskaplike werk social worker maatskaplike werker community development gemeenskap outreach welfare welsyn youth work case worker probation ngo field work',
  'Childcare & Early Childhood Development': 'childcare kinderversorging creche crèche daycare preschool kleuterskool nursery school ecd early childhood au pair aupair nanny kindergarten playgroup',
  'Translation, Language & Localisation': 'translation vertaling translator vertaler interpreter tolk language taal localisation localization proofreading proefleser editing subtitling transcription copy editing linguist',
  'Between roles': 'unemployed werkloos between jobs job seeking looking for work not working career break gap year sabbatical',
  'Homemaker & Caregiver': 'homemaker housewife huisvrou stay at home parent caregiver versorger carer full time parent home executive',
  'Retired': 'retired afgetree pensioner pensioenaris pension emeritus',
  'Student': 'student studeer studying scholar leerling learner intern internship candidate articles postgraduate undergraduate university studie',
}

// Curated list of major South African cities/towns, so the directory filter
// stays clean instead of accumulating "Cape Town" / "CPT" / "Kaapstad" as
// separate values. Profiles outside SA still use free text — see Profile.jsx.
export const SA_CITIES = [
  'Cape Town', 'Stellenbosch', 'Paarl', 'Somerset West', 'Bellville',
  'Durbanville', 'Kuils River', 'Brackenfell', 'Parow', 'Goodwood',
  'Milnerton', 'Table View', 'Constantia', 'Claremont', 'Rondebosch',
  'Sea Point', 'Camps Bay', 'Hermanus', 'Worcester', 'Wellington',
  'Franschhoek', 'George', 'Knysna', 'Mossel Bay', 'Oudtshoorn',
  'Saldanha', 'Vredenburg', 'Malmesbury',
  'Johannesburg', 'Sandton', 'Randburg', 'Roodepoort', 'Centurion',
  'Pretoria', 'Midrand', 'Benoni', 'Boksburg', 'Krugersdorp',
  'Durban', 'Umhlanga', 'Pietermaritzburg', 'Ballito',
  'Gqeberha (Port Elizabeth)', 'East London',
  'Bloemfontein', 'Kimberley', 'Polokwane', 'Nelspruit (Mbombela)',
  'Rustenburg', 'Potchefstroom', 'Mahikeng',
]

export const COUNTRIES = [
  'Afghanistan','Albania','Algeria','Andorra','Angola','Antigua and Barbuda',
  'Argentina','Armenia','Australia','Austria','Azerbaijan',
  'Bahamas','Bahrain','Bangladesh','Barbados','Belarus','Belgium','Belize',
  'Benin','Bhutan','Bolivia','Bosnia and Herzegovina','Botswana','Brazil',
  'Brunei','Bulgaria','Burkina Faso','Burundi',
  'Cambodia','Cameroon','Canada','Cape Verde','Central African Republic',
  'Chad','Chile','China','Colombia','Comoros','Congo','Costa Rica',
  'Croatia','Cuba','Cyprus','Czech Republic',
  'Democratic Republic of the Congo','Denmark','Djibouti','Dominica',
  'Dominican Republic',
  'East Timor','Ecuador','Egypt','El Salvador','Equatorial Guinea','Eritrea',
  'Estonia','Eswatini','Ethiopia',
  'Fiji','Finland','France',
  'Gabon','Gambia','Georgia','Germany','Ghana','Greece','Grenada','Guatemala',
  'Guinea','Guinea-Bissau','Guyana',
  'Haiti','Honduras','Hungary',
  'Iceland','India','Indonesia','Iran','Iraq','Ireland','Israel','Italy',
  'Ivory Coast',
  'Jamaica','Japan','Jordan',
  'Kazakhstan','Kenya','Kiribati','Kuwait','Kyrgyzstan',
  'Laos','Latvia','Lebanon','Lesotho','Liberia','Libya','Liechtenstein',
  'Lithuania','Luxembourg',
  'Madagascar','Malawi','Malaysia','Maldives','Mali','Malta','Mauritania',
  'Mauritius','Mexico','Moldova','Monaco','Mongolia','Montenegro','Morocco',
  'Mozambique','Myanmar',
  'Namibia','Nepal','Netherlands','New Zealand','Nicaragua','Niger','Nigeria',
  'North Korea','North Macedonia','Norway',
  'Oman',
  'Pakistan','Panama','Papua New Guinea','Paraguay','Peru','Philippines',
  'Poland','Portugal',
  'Qatar',
  'Romania','Russia','Rwanda',
  'Saint Kitts and Nevis','Saint Lucia','Saint Vincent and the Grenadines',
  'Samoa','Saudi Arabia','Senegal','Serbia','Seychelles','Sierra Leone',
  'Singapore','Slovakia','Slovenia','Solomon Islands','Somalia',
  'South Africa','South Korea','South Sudan','Spain','Sri Lanka','Sudan',
  'Suriname','Sweden','Switzerland','Syria',
  'Taiwan','Tajikistan','Tanzania','Thailand','Togo','Tonga',
  'Trinidad and Tobago','Tunisia','Turkey','Turkmenistan',
  'Uganda','Ukraine','United Arab Emirates','United Kingdom',
  'United States','Uruguay','Uzbekistan',
  'Vanuatu','Vatican City','Venezuela','Vietnam',
  'Yemen',
  'Zambia','Zimbabwe',
]

// Dial codes for PhoneInput.jsx — one row per entry in COUNTRIES above
// (name kept identical so the two lists can be cross-referenced), plus an
// ISO 3166-1 alpha-2 code the flag emoji is derived from at render time.
// `format` is an optional "what it looks like locally" example shown as
// the field's placeholder once that country is picked — only filled in for
// the handful of countries SACS alumni are actually likely to be in;
// everywhere else falls back to a generic placeholder.
// Shape: [name, iso2, dialCode, format?]
export const COUNTRY_DIAL_CODES = [
  ['Afghanistan', 'AF', '93'],
  ['Albania', 'AL', '355'],
  ['Algeria', 'DZ', '213'],
  ['Andorra', 'AD', '376'],
  ['Angola', 'AO', '244'],
  ['Antigua and Barbuda', 'AG', '1268'],
  ['Argentina', 'AR', '54'],
  ['Armenia', 'AM', '374'],
  ['Australia', 'AU', '61', '412 345 678'],
  ['Austria', 'AT', '43'],
  ['Azerbaijan', 'AZ', '994'],
  ['Bahamas', 'BS', '1242'],
  ['Bahrain', 'BH', '973'],
  ['Bangladesh', 'BD', '880'],
  ['Barbados', 'BB', '1246'],
  ['Belarus', 'BY', '375'],
  ['Belgium', 'BE', '32', '470 12 34 56'],
  ['Belize', 'BZ', '501'],
  ['Benin', 'BJ', '229'],
  ['Bhutan', 'BT', '975'],
  ['Bolivia', 'BO', '591'],
  ['Bosnia and Herzegovina', 'BA', '387'],
  ['Botswana', 'BW', '267'],
  ['Brazil', 'BR', '55'],
  ['Brunei', 'BN', '673'],
  ['Bulgaria', 'BG', '359'],
  ['Burkina Faso', 'BF', '226'],
  ['Burundi', 'BI', '257'],
  ['Cambodia', 'KH', '855'],
  ['Cameroon', 'CM', '237'],
  ['Canada', 'CA', '1', '(416) 555-0134'],
  ['Cape Verde', 'CV', '238'],
  ['Central African Republic', 'CF', '236'],
  ['Chad', 'TD', '235'],
  ['Chile', 'CL', '56'],
  ['China', 'CN', '86'],
  ['Colombia', 'CO', '57'],
  ['Comoros', 'KM', '269'],
  ['Congo', 'CG', '242'],
  ['Costa Rica', 'CR', '506'],
  ['Croatia', 'HR', '385'],
  ['Cuba', 'CU', '53'],
  ['Cyprus', 'CY', '357'],
  ['Czech Republic', 'CZ', '420'],
  ['Democratic Republic of the Congo', 'CD', '243'],
  ['Denmark', 'DK', '45'],
  ['Djibouti', 'DJ', '253'],
  ['Dominica', 'DM', '1767'],
  ['Dominican Republic', 'DO', '1809'],
  ['East Timor', 'TL', '670'],
  ['Ecuador', 'EC', '593'],
  ['Egypt', 'EG', '20'],
  ['El Salvador', 'SV', '503'],
  ['Equatorial Guinea', 'GQ', '240'],
  ['Eritrea', 'ER', '291'],
  ['Estonia', 'EE', '372'],
  ['Eswatini', 'SZ', '268'],
  ['Ethiopia', 'ET', '251'],
  ['Fiji', 'FJ', '679'],
  ['Finland', 'FI', '358'],
  ['France', 'FR', '33', '6 12 34 56 78'],
  ['Gabon', 'GA', '241'],
  ['Gambia', 'GM', '220'],
  ['Georgia', 'GE', '995'],
  ['Germany', 'DE', '49', '151 2345 6789'],
  ['Ghana', 'GH', '233'],
  ['Greece', 'GR', '30'],
  ['Grenada', 'GD', '1473'],
  ['Guatemala', 'GT', '502'],
  ['Guinea', 'GN', '224'],
  ['Guinea-Bissau', 'GW', '245'],
  ['Guyana', 'GY', '592'],
  ['Haiti', 'HT', '509'],
  ['Honduras', 'HN', '504'],
  ['Hungary', 'HU', '36'],
  ['Iceland', 'IS', '354'],
  ['India', 'IN', '91', '81234 56789'],
  ['Indonesia', 'ID', '62'],
  ['Iran', 'IR', '98'],
  ['Iraq', 'IQ', '964'],
  ['Ireland', 'IE', '353', '85 123 4567'],
  ['Israel', 'IL', '972'],
  ['Italy', 'IT', '39'],
  ['Ivory Coast', 'CI', '225'],
  ['Jamaica', 'JM', '1876'],
  ['Japan', 'JP', '81'],
  ['Jordan', 'JO', '962'],
  ['Kazakhstan', 'KZ', '7'],
  ['Kenya', 'KE', '254', '712 345 678'],
  ['Kiribati', 'KI', '686'],
  ['Kuwait', 'KW', '965'],
  ['Kyrgyzstan', 'KG', '996'],
  ['Laos', 'LA', '856'],
  ['Latvia', 'LV', '371'],
  ['Lebanon', 'LB', '961'],
  ['Lesotho', 'LS', '266'],
  ['Liberia', 'LR', '231'],
  ['Libya', 'LY', '218'],
  ['Liechtenstein', 'LI', '423'],
  ['Lithuania', 'LT', '370'],
  ['Luxembourg', 'LU', '352'],
  ['Madagascar', 'MG', '261'],
  ['Malawi', 'MW', '265'],
  ['Malaysia', 'MY', '60'],
  ['Maldives', 'MV', '960'],
  ['Mali', 'ML', '223'],
  ['Malta', 'MT', '356'],
  ['Mauritania', 'MR', '222'],
  ['Mauritius', 'MU', '230'],
  ['Mexico', 'MX', '52'],
  ['Moldova', 'MD', '373'],
  ['Monaco', 'MC', '377'],
  ['Mongolia', 'MN', '976'],
  ['Montenegro', 'ME', '382'],
  ['Morocco', 'MA', '212'],
  ['Mozambique', 'MZ', '258'],
  ['Myanmar', 'MM', '95'],
  ['Namibia', 'NA', '264', '81 123 4567'],
  ['Nepal', 'NP', '977'],
  ['Netherlands', 'NL', '31', '6 12345678'],
  ['New Zealand', 'NZ', '64', '21 123 4567'],
  ['Nicaragua', 'NI', '505'],
  ['Niger', 'NE', '227'],
  ['Nigeria', 'NG', '234', '802 123 4567'],
  ['North Korea', 'KP', '850'],
  ['North Macedonia', 'MK', '389'],
  ['Norway', 'NO', '47'],
  ['Oman', 'OM', '968'],
  ['Pakistan', 'PK', '92'],
  ['Panama', 'PA', '507'],
  ['Papua New Guinea', 'PG', '675'],
  ['Paraguay', 'PY', '595'],
  ['Peru', 'PE', '51'],
  ['Philippines', 'PH', '63'],
  ['Poland', 'PL', '48'],
  ['Portugal', 'PT', '351'],
  ['Qatar', 'QA', '974'],
  ['Romania', 'RO', '40'],
  ['Russia', 'RU', '7'],
  ['Rwanda', 'RW', '250'],
  ['Saint Kitts and Nevis', 'KN', '1869'],
  ['Saint Lucia', 'LC', '1758'],
  ['Saint Vincent and the Grenadines', 'VC', '1784'],
  ['Samoa', 'WS', '685'],
  ['Saudi Arabia', 'SA', '966'],
  ['Senegal', 'SN', '221'],
  ['Serbia', 'RS', '381'],
  ['Seychelles', 'SC', '248'],
  ['Sierra Leone', 'SL', '232'],
  ['Singapore', 'SG', '65'],
  ['Slovakia', 'SK', '421'],
  ['Slovenia', 'SI', '386'],
  ['Solomon Islands', 'SB', '677'],
  ['Somalia', 'SO', '252'],
  ['South Africa', 'ZA', '27', '82 123 4567'],
  ['South Korea', 'KR', '82'],
  ['South Sudan', 'SS', '211'],
  ['Spain', 'ES', '34'],
  ['Sri Lanka', 'LK', '94'],
  ['Sudan', 'SD', '249'],
  ['Suriname', 'SR', '597'],
  ['Sweden', 'SE', '46'],
  ['Switzerland', 'CH', '41'],
  ['Syria', 'SY', '963'],
  ['Taiwan', 'TW', '886'],
  ['Tajikistan', 'TJ', '992'],
  ['Tanzania', 'TZ', '255'],
  ['Thailand', 'TH', '66'],
  ['Togo', 'TG', '228'],
  ['Tonga', 'TO', '676'],
  ['Trinidad and Tobago', 'TT', '1868'],
  ['Tunisia', 'TN', '216'],
  ['Turkey', 'TR', '90'],
  ['Turkmenistan', 'TM', '993'],
  ['Uganda', 'UG', '256'],
  ['Ukraine', 'UA', '380'],
  ['United Arab Emirates', 'AE', '971', '50 123 4567'],
  ['United Kingdom', 'GB', '44', '7911 123456'],
  ['United States', 'US', '1', '(415) 555-2671'],
  ['Uruguay', 'UY', '598'],
  ['Uzbekistan', 'UZ', '998'],
  ['Vanuatu', 'VU', '678'],
  ['Vatican City', 'VA', '379'],
  ['Venezuela', 'VE', '58'],
  ['Vietnam', 'VN', '84'],
  ['Yemen', 'YE', '967'],
  ['Zambia', 'ZM', '260'],
  ['Zimbabwe', 'ZW', '263', '77 123 4567'],
]

// Shown pinned above the alphabetical list in PhoneInput's country dropdown
// — South Africa first since that's home turf for most SACS alumni, then
// a few of the other countries alumni most commonly end up in.
export const PHONE_PRIORITY_COUNTRIES = [
  'South Africa', 'United Kingdom', 'United States', 'Netherlands',
  'Australia', 'United Arab Emirates', 'Canada', 'New Zealand',
]

// Mentoring section options
// Generic fallback list — shown before an industry is picked, or when the
// chosen industry has no dedicated list below.
export const EXPERTISE_OPTIONS = [
  'Strategy & Business Development',
  'Finance & Investment',
  'Technology & Software',
  'Marketing & Sales',
  'Operations & Supply Chain',
  'Human Resources',
  'Legal & Compliance',
  'Engineering & Manufacturing',
  'Hospitality & Tourism',
  'Real Estate & Construction',
  'Agriculture & Food',
  'Education & Training',
  'Healthcare & Wellness',
  'Creative & Design',
  'Import/Export & Trade',
  'Non-Profit Management',
]

// Area-of-expertise options, tailored per industry (keys match INDUSTRIES
// exactly). Profile.jsx looks up the list for whatever industry is selected
// and falls back to EXPERTISE_OPTIONS if there isn't a dedicated one yet.
export const EXPERTISE_BY_INDUSTRY = {
  'Accounting & Finance': [
    'Financial Accounting & Reporting', 'Management Accounting', 'Corporate Tax', 'Personal Tax',
    'Auditing & Assurance', 'Bookkeeping', 'Payroll', 'Financial Planning & Analysis (FP&A)',
    'Treasury & Cash Management', 'Forensic Accounting', 'Budgeting', 'IFRS/GAAP Compliance',
    'Cost Accounting',
  ],
  'Agriculture & Wine': [
    'Viticulture', 'Winemaking & Oenology', 'Crop Production', 'Livestock Farming',
    'Agribusiness Management', 'Farm Operations', 'Agricultural Economics', 'Soil Science & Agronomy',
    'Irrigation & Water Management', 'Food Safety & Quality Control', 'Export & Trade (Agri Products)',
    'Sustainable/Organic Farming',
  ],
  'Architecture & Design': [
    'Residential Architecture', 'Commercial/Corporate Architecture', 'Urban Planning',
    'Interior Design', 'Landscape Architecture', 'Heritage & Restoration',
    'Sustainable/Green Building Design', '3D Visualisation & BIM', 'Construction Documentation',
    'Design Project Management', 'Product Design',
  ],
  'Civil Engineering': [
    'Structural Engineering', 'Geotechnical Engineering', 'Transportation/Roads Engineering',
    'Water & Sanitation Engineering', 'Bridges & Infrastructure', 'Project Management',
    'Construction Supervision', 'Surveying', 'Environmental Engineering', 'Municipal Engineering',
    'Site & Civil Design',
  ],
  'Software Engineering & Development': [
    'Frontend Development', 'Backend Development', 'Full-Stack Development', 'Mobile App Development',
    'DevOps & Infrastructure', 'Cloud Computing (AWS/Azure/GCP)', 'Data Engineering',
    'Machine Learning/AI', 'Cybersecurity', 'QA & Testing', 'Product Management (Tech)',
    'Engineering Leadership/CTO', 'UX/UI Engineering', 'Blockchain/Web3',
  ],
  'Mechanical/Manufacturing Engineering': [
    'Product Design & CAD', 'Process Engineering', 'Quality Assurance/Control',
    'Industrial Automation', 'Maintenance Engineering', 'Manufacturing Operations', 'HVAC Systems',
    'Tooling & Machining', 'Lean Manufacturing/Six Sigma', 'Robotics', 'Plant Management',
  ],
  'Other Engineering (electrical, chemical, marine, etc.)': [
    'Electrical Engineering', 'Chemical Engineering', 'Marine Engineering', 'Aerospace Engineering',
    'Mining Engineering', 'Industrial Engineering', 'Control & Instrumentation',
    'Renewable Energy Systems', 'Telecommunications Engineering', 'Process Design', 'Power Systems',
  ],
  'Banking & Financial Services': [
    'Retail Banking', 'Corporate/Commercial Banking', 'Private Banking & Wealth Management',
    'Credit & Risk Management', 'Treasury', 'Compliance & AML', 'Payments & Digital Banking',
    'Relationship Management', 'Trade Finance', 'Branch/Operations Management',
  ],
  'Insurance & Actuarial Science': [
    'Life Insurance', 'Short-Term/Personal Insurance', 'Underwriting', 'Claims Management',
    'Actuarial Modelling', 'Risk Assessment', 'Reinsurance', 'Insurance Broking',
    'Employee Benefits', 'Product Development (Insurance)',
  ],
  'Investment & Asset Management': [
    'Portfolio Management', 'Equity Research', 'Private Equity', 'Venture Capital', 'Hedge Funds',
    'Wealth Management', 'Financial Modelling & Valuation', 'Fund Administration',
    'Alternative Investments', 'Fixed Income',
  ],
  'Construction & Project Management': [
    'Site Management', 'Quantity Surveying', 'Project Scheduling & Planning',
    'Health & Safety (Construction)', 'Contracts Management', 'Cost Estimation',
    'Building Contracting', 'Civils/Infrastructure Delivery', 'Facilities Management',
    'Renovations & Fit-Outs',
  ],
  'Property & Real Estate': [
    'Residential Sales', 'Commercial Property', 'Property Development', 'Property Management',
    'Real Estate Investment', 'Property Valuation', 'Leasing/Letting',
    'Property Law & Conveyancing', 'Facilities Management', 'Real Estate Finance',
  ],
  'Legal': [
    'Corporate & Commercial Law', 'Litigation & Dispute Resolution', 'Property/Conveyancing Law',
    'Family Law', 'Criminal Law', 'Labour/Employment Law', 'Tax Law', 'Intellectual Property Law',
    'Mergers & Acquisitions', 'Compliance & Regulatory', 'Contract Drafting & Negotiation',
    'Banking & Finance Law',
  ],
  'Consulting': [
    'Strategy Consulting', 'Management Consulting', 'Financial/Risk Consulting',
    'IT/Technology Consulting', 'HR Consulting', 'Operations Consulting', 'Change Management',
    'Business Process Improvement', 'M&A Advisory', 'Sustainability/ESG Consulting',
  ],
  'Management & Operations': [
    'General Management', 'Operations Management', 'Business Strategy', 'Supply Chain Management',
    'Process Improvement', 'Team Leadership', 'Project/Programme Management', 'Change Management',
    'Performance Management', 'Business Development',
  ],
  'Human Resources & Recruitment': [
    'Talent Acquisition/Recruitment', 'HR Business Partnering', 'Learning & Development',
    'Compensation & Benefits', 'Employee Relations', 'Organisational Development',
    'HR Policy & Compliance', 'Performance Management', 'Employer Branding', 'Executive Search',
  ],
  'Marketing & Advertising': [
    'Brand Management', 'Digital Marketing', 'Social Media Marketing', 'Content Marketing',
    'Advertising Campaigns', 'Market Research', 'Product Marketing', 'Growth Marketing',
    'Email/CRM Marketing', 'SEO/SEM', 'Creative Direction',
  ],
  'Media & Creative (publishing, film, design)': [
    'Graphic Design', 'Film & Video Production', 'Photography', 'Journalism/Editorial', 'Publishing',
    'Copywriting', 'Animation & Motion Graphics', 'Broadcasting', 'Music Production', 'Illustration',
    'Content Creation',
  ],
  'Public Relations & Communications': [
    'Media Relations', 'Corporate Communications', 'Crisis Communications',
    'Internal Communications', 'Reputation Management', 'Event Management',
    'Stakeholder Engagement', 'Speechwriting', 'Public Affairs', 'Social Media Communications',
  ],
  'Education & Academia': [
    'Primary/Secondary Teaching', 'Higher Education/Lecturing', 'Curriculum Development',
    'Educational Leadership/Admin', 'Academic Research', 'Tutoring', 'Special Needs Education',
    'EdTech', 'Training & Facilitation', 'School Governance',
  ],
  'Research & Development': [
    'Scientific Research', 'Product R&D', 'Innovation Management', 'Applied Research',
    'Data Analysis & Statistics', 'Laboratory Management', 'Grant Writing/Funding',
    'Prototyping & Testing', 'Technology Transfer',
  ],
  'Healthcare & Medical': [
    'General Practice/Medicine', 'Surgery', 'Nursing', 'Specialist Medicine', 'Dentistry',
    'Physiotherapy', 'Radiology', 'Emergency Medicine', 'Healthcare Administration', 'Public Health',
    'Medical Research', 'Occupational Therapy',
  ],
  'Pharmaceuticals & Biotech': [
    'Drug Development', 'Clinical Research/Trials', 'Regulatory Affairs', 'Pharmacovigilance',
    'Pharmaceutical Sales', 'Biotechnology Research', 'Quality Assurance (Pharma)',
    'Manufacturing (Pharma)', 'Pharmacy',
  ],
  'Mental Health & Psychology': [
    'Clinical Psychology', 'Counselling', 'Psychiatry', 'Occupational/Organisational Psychology',
    'Educational Psychology', 'Family/Marriage Therapy', 'Substance Abuse Counselling',
    'Trauma Therapy', 'Life/Executive Coaching', 'Child & Adolescent Psychology',
  ],
  'Energy & Environment': [
    'Renewable Energy (Solar/Wind)', 'Oil & Gas', 'Energy Efficiency', 'Environmental Management',
    'Sustainability & ESG', 'Climate Change/Carbon', 'Water Resource Management', 'Waste Management',
    'Environmental Compliance', 'Power Generation',
  ],
  'Mining & Resources': [
    'Mine Management', 'Geology', 'Mining Engineering', 'Metallurgy', 'Mineral Processing',
    'Mine Safety', 'Mining Finance', 'Exploration', 'Resource Economics',
    'Environmental Rehabilitation',
  ],
  'Manufacturing & Industrial': [
    'Production Management', 'Quality Control', 'Supply Chain/Procurement', 'Industrial Engineering',
    'Health & Safety', 'Plant Operations', 'Automation', 'Lean Manufacturing/Six Sigma',
    'Product Development', 'Maintenance & Reliability',
  ],
  'Hospitality & Tourism': [
    'Hotel Management', 'Guest Services/Front Office', 'Food & Beverage Management',
    'Event Management', 'Tour Operations/Travel', 'Tourism Marketing', 'Restaurant Management',
    'Guiding', 'Hospitality Training', 'Resort/Lodge Management',
  ],
  'Food & Beverage': [
    'Food Production', 'Culinary Arts/Chef', 'Beverage Production', 'Food Safety & Quality',
    'Product Development (Food)', 'Supply Chain (F&B)', 'Restaurant/Catering Management',
    'Nutrition', 'Retail F&B', 'Brewing/Distilling',
  ],
  'Retail & Wholesale': [
    'Store Management', 'Merchandising', 'Buying & Procurement', 'Retail Operations',
    'Category Management', 'Visual Merchandising', 'Wholesale Distribution', 'Customer Experience',
    'Inventory Management', 'Franchise Management',
  ],
  'E-commerce': [
    'Online Store Management', 'Digital Marketing (E-commerce)',
    'Marketplace Management (Amazon/Takealot etc.)', 'Fulfilment & Logistics',
    'Conversion Rate Optimisation', 'UX for E-commerce', 'Payment Systems', 'Dropshipping',
    'Product Listing/Cataloguing', 'Customer Service (E-commerce)',
  ],
  'Transport & Logistics': [
    'Supply Chain Management', 'Freight Forwarding', 'Fleet Management', 'Warehouse Management',
    'Distribution & Delivery', 'Shipping/Maritime', 'Import/Export', 'Logistics Planning',
    'Procurement & Sourcing', 'Route Optimisation',
  ],
  'Telecommunications': [
    'Network Engineering', 'Telecoms Infrastructure', 'Mobile/Wireless Technology', 'Fibre/Broadband',
    'Telecoms Sales', 'RF Engineering', 'Systems Integration', 'Telecoms Regulation',
    'Customer Support (Telecoms)',
  ],
  'Utilities & Water': [
    'Water Treatment & Supply', 'Electricity Distribution', 'Utility Operations',
    'Infrastructure Maintenance', 'Metering & Billing', 'Regulatory Compliance (Utilities)',
    'Wastewater Management', 'Grid Management', 'Renewable Integration',
  ],
  'Government & Public Sector': [
    'Public Policy', 'Public Administration', 'Municipal Government', 'Diplomacy/Foreign Service',
    'Law Enforcement', 'Public Finance', 'Urban/Regional Planning', 'Regulatory Affairs',
    'Political Advisory', 'Social Services',
  ],
  'Non-profit & NGO': [
    'Programme Management', 'Fundraising & Donor Relations', 'Community Development',
    'Advocacy & Policy', 'Volunteer Management', 'Grant Writing', 'Humanitarian Aid',
    'Monitoring & Evaluation', 'NGO Leadership/Governance', 'Social Impact Strategy',
  ],
  'Sport & Recreation': [
    'Coaching', 'Sports Management', 'Sports Science', 'Sports Marketing/Sponsorship',
    'Personal Training/Fitness', 'Sports Administration', 'Event/Tournament Management',
    'Talent Development', 'Sports Broadcasting', 'Sports Physiotherapy',
  ],
  'Arts & Entertainment': [
    'Performing Arts (Theatre/Dance)', 'Music', 'Film & TV Production', 'Visual Arts',
    'Event/Concert Production', 'Talent Management', 'Curation/Gallery Management',
    'Entertainment Law', 'Creative Writing', 'Arts Administration',
  ],
  'Military & Defence': [
    'Combat/Operations', 'Military Logistics', 'Defence Intelligence', 'Cybersecurity/Defence Tech',
    'Military Engineering', 'Naval/Maritime Operations', 'Aviation/Air Force Operations',
    'Defence Procurement', 'Strategic Planning', 'Veteran Affairs',
  ],
  'Information Technology & IT Services': [
    'IT Support & Helpdesk', 'Systems Administration', 'Network Administration',
    'Server & Infrastructure', 'Cloud Administration', 'ERP Systems (SAP, Sage, etc.)',
    'CRM Systems (Salesforce, HubSpot)', 'IT Project Management', 'Business Systems Analysis',
    'Hardware & Endpoint Management', 'Database Administration', 'IT Procurement & Vendor Management',
    'Managed Services (MSP)',
  ],
  'Data, Analytics & AI': [
    'Data Analysis', 'Business Intelligence & Reporting', 'Data Science',
    'Machine Learning & AI', 'Data Engineering & Pipelines', 'Data Warehousing',
    'SQL & Database Querying', 'Statistical Modelling', 'Dashboarding (Power BI, Tableau)',
    'Data Governance & Quality', 'Forecasting & Demand Planning', 'Experimentation & A/B Testing',
  ],
  'Cybersecurity & Information Security': [
    'Security Operations (SOC)', 'Penetration Testing & Red Team', 'Incident Response & Forensics',
    'Governance, Risk & Compliance (GRC)', 'Identity & Access Management', 'Network Security',
    'Cloud Security', 'Application Security', 'Security Awareness & Training',
    'POPIA/GDPR Compliance', 'ISO 27001 & Audits', 'Threat Intelligence',
  ],
  'Gaming & Esports': [
    'Game Development', 'Game Design', 'Game Art & Animation', 'Unity/Unreal Engineering',
    'Level Design', 'QA & Playtesting', 'Community Management', 'Esports Team Management',
    'Streaming & Content Creation', 'Game Publishing & Monetisation', 'Audio & Sound Design',
  ],
  'Sales & Business Development': [
    'New Business Development', 'Account Management', 'Key Account Management',
    'B2B Sales', 'B2C/Retail Sales', 'Technical/Solution Sales', 'Inside Sales & Telesales',
    'Sales Management & Team Leadership', 'Channel & Partner Sales', 'Sales Strategy & Planning',
    'CRM & Pipeline Management', 'Tender & Proposal Writing', 'Negotiation & Closing',
  ],
  'Procurement & Supply Chain': [
    'Strategic Sourcing', 'Purchasing & Buying', 'Supplier Relationship Management',
    'Contract Negotiation', 'Tender & Bid Management', 'Inventory & Stock Control',
    'Demand & Supply Planning', 'Warehouse Management', 'Import/Export & Customs',
    'Category Management', 'Cost Reduction & Spend Analysis', 'BBBEE & Supplier Development',
  ],
  'Customer Service & Call Centres': [
    'Inbound Customer Support', 'Outbound & Telesales', 'Technical Support',
    'Complaints & Escalation Handling', 'Customer Success & Retention', 'Team Leadership & Coaching',
    'Workforce Planning & Scheduling', 'Quality Assurance & Monitoring', 'CRM & Ticketing Systems',
    'BPO Operations', 'Customer Experience (CX) Design',
  ],
  'Administration & Office Support': [
    'Office Management', 'Executive & Personal Assistance', 'Reception & Front of House',
    'Diary & Travel Coordination', 'Minute Taking & Board Support', 'Data Capture & Records Management',
    'Filing & Document Control', 'Invoicing & Petty Cash', 'Procurement of Office Supplies',
    'Switchboard & Correspondence',
  ],
  'Entrepreneurship & Startups': [
    'Founding & Company Building', 'Fundraising & Investor Relations', 'Product-Market Fit',
    'Business Model Design', 'Go-to-Market Strategy', 'Bootstrapping & Cash Flow Management',
    'Small Business Operations', 'Franchising', 'Freelancing & Consulting',
    'Scaling & Hiring', 'Exits & Acquisitions', 'Pitching & Storytelling',
  ],
  'Events & Conference Management': [
    'Conference & Seminar Management', 'Wedding Planning', 'Corporate Functions',
    'Exhibition & Expo Management', 'Venue Sourcing & Management', 'Event Production & AV',
    'Sponsorship & Exhibitor Sales', 'Delegate & Guest Management', 'Event Catering Coordination',
    'Event Budgeting & Logistics', 'Festival & Live Event Operations',
  ],
  'Design (Graphic, UX & Product)': [
    'Graphic Design', 'Brand & Identity Design', 'UX Research', 'UI Design',
    'Product Design', 'Web Design', 'Illustration', 'Motion Graphics & Animation',
    'Typography', 'Packaging Design', 'Design Systems', 'Prototyping (Figma, etc.)',
    'Print & Layout Design', 'Art Direction',
  ],
  'Photography & Videography': [
    'Portrait Photography', 'Wedding & Event Photography', 'Commercial & Product Photography',
    'Wildlife & Nature Photography', 'Photojournalism', 'Videography & Cinematography',
    'Video Editing & Post-Production', 'Drone/Aerial Work', 'Studio Lighting',
    'Colour Grading', 'Content Creation for Social Media',
  ],
  'Fashion, Apparel & Textiles': [
    'Fashion Design', 'Pattern Making & Grading', 'Garment Manufacturing', 'Textile Sourcing',
    'Tailoring & Alterations', 'Fashion Buying & Merchandising', 'Retail Fashion Management',
    'Styling & Wardrobe', 'Fashion Marketing & PR', 'Sustainable & Ethical Fashion',
    'Footwear & Accessories',
  ],
  'Printing & Packaging': [
    'Offset & Litho Printing', 'Digital Printing', 'Large Format & Signage', 'Screen Printing',
    'Packaging Design & Structure', 'Labelling & Barcoding', 'Prepress & Artwork',
    'Bindery & Finishing', 'Print Estimating & Production Management', 'Substrates & Materials',
  ],
  'Aviation & Aerospace': [
    'Commercial Piloting', 'Private/Charter Piloting', 'Flight Instruction',
    'Cabin Crew & In-Flight Service', 'Air Traffic Control', 'Aircraft Maintenance (AME)',
    'Avionics', 'Airline Operations & Dispatch', 'Airport Management & Ground Handling',
    'Aviation Safety & Regulation', 'Aerospace Engineering', 'Drones & UAV Operations',
  ],
  'Automotive': [
    'Vehicle Sales', 'Dealership Management', 'Mechanical Repair & Servicing',
    'Auto Electrics & Diagnostics', 'Panel Beating & Spray Painting', 'Parts & Accessories',
    'Fleet Management', 'Automotive Manufacturing & Assembly', 'Motorsport & Performance Tuning',
    'Vehicle Finance & Insurance', 'Workshop Management',
  ],
  'Maritime & Shipping': [
    'Deck Operations & Navigation', 'Marine Engineering', 'Port & Harbour Operations',
    'Ship Chandling & Agency', 'Freight Forwarding & Chartering', 'Stevedoring & Cargo Handling',
    'Maritime Safety & Compliance', 'Vessel Maintenance & Repair', 'Yachting & Charter',
    'Marine Surveying', 'Customs & Documentation',
  ],
  'Skilled Trades (plumbing, electrical, carpentry)': [
    'Plumbing', 'Electrical Installation & Wiring', 'Carpentry & Joinery', 'Welding & Boilermaking',
    'Fitting & Turning', 'Bricklaying & Plastering', 'Tiling', 'Painting & Decorating',
    'Roofing', 'HVAC & Refrigeration', 'Cabinet Making', 'Glazing & Aluminium',
    'Solar Installation', 'Trade Supervision & Estimating', 'Apprentice Training',
  ],
  'Facilities Management & Cleaning': [
    'Building & Property Maintenance', 'Cleaning Operations', 'Hygiene Services',
    'Pest Control', 'Landscaping & Grounds Maintenance', 'Health & Safety Compliance',
    'Contract & Vendor Management', 'Energy & Utilities Management', 'Soft Services Management',
    'Caretaking & Site Supervision',
  ],
  'Security Services & Risk': [
    'Guarding & Manned Security', 'Armed Response', 'Alarm & CCTV Systems',
    'Access Control', 'Risk Assessment & Management', 'Investigations & Loss Prevention',
    'Close Protection', 'Security Operations Management', 'Cash-in-Transit',
    'Event Security', 'Business Continuity Planning',
  ],
  'Emergency Services (police, fire, paramedic)': [
    'Policing & Patrol', 'Criminal Investigation', 'Traffic & Metro Policing',
    'Firefighting & Rescue', 'Emergency Medical Services (EMS)', 'Advanced Life Support',
    'Disaster & Incident Management', 'Emergency Call Dispatch', 'Search & Rescue',
    'Fire Safety & Inspection', 'Forensic Services',
  ],
  'Waste Management & Recycling': [
    'Waste Collection & Refuse Operations', 'Recycling Operations', 'Landfill Management',
    'Hazardous Waste Handling', 'Scrap Metal & Materials Trading', 'Waste Minimisation Consulting',
    'Environmental Compliance', 'Circular Economy & Reuse', 'Composting & Organic Waste',
  ],
  'Beauty, Wellness & Personal Care': [
    'Hairdressing & Styling', 'Barbering', 'Nail Technology', 'Skincare & Facials',
    'Make-Up Artistry', 'Massage Therapy', 'Spa Management', 'Aesthetics & Advanced Treatments',
    'Salon Ownership & Management', 'Cosmetics Retail & Training', 'Wellness Coaching',
  ],
  'Funeral Services': [
    'Funeral Directing', 'Mortuary Science & Embalming', 'Bereavement Support',
    'Cremation Services', 'Funeral Policy & Insurance', 'Memorial & Service Planning',
    'Repatriation & Documentation', 'Funeral Home Management',
  ],
  'Veterinary & Animal Care': [
    'Veterinary Medicine', 'Veterinary Nursing', 'Veterinary Surgery', 'Equine Care',
    'Livestock & Production Animal Health', 'Wildlife & Game Management', 'Animal Behaviour & Training',
    'Grooming & Kennels', 'Animal Welfare & Rescue', 'Veterinary Practice Management',
    'Animal Nutrition',
  ],
  'Forestry & Fishing': [
    'Plantation & Forest Management', 'Timber Harvesting & Logging', 'Sawmilling & Timber Processing',
    'Silviculture', 'Forest Certification & Compliance', 'Commercial Fishing Operations',
    'Fisheries Management & Quotas', 'Aquaculture & Mariculture', 'Seafood Processing & Export',
    'Marine Resource Conservation',
  ],
  'Religion & Ministry': [
    'Pastoral Ministry', 'Preaching & Teaching', 'Youth Ministry', 'Worship & Music Ministry',
    'Missions & Outreach', 'Chaplaincy', 'Church Administration', 'Theology & Biblical Studies',
    'Pastoral Counselling', 'Small Group & Discipleship Leadership', 'Church Planting',
  ],
  'Social Work & Community Development': [
    'Statutory Social Work', 'Child Protection & Family Services', 'Community Development',
    'Youth Work', 'Substance Abuse & Rehabilitation', 'Case Management',
    'Probation & Correctional Services', 'Poverty Alleviation Programmes', 'Advocacy & Rights',
    'Programme Monitoring & Evaluation', 'Volunteer Coordination',
  ],
  'Childcare & Early Childhood Development': [
    'Early Childhood Development (ECD)', 'Preschool & Grade R Teaching', 'Creche & Daycare Management',
    'Curriculum Design (Early Years)', 'Child Psychology & Development', 'Special Needs Support',
    'Au Pairing & Nannying', 'Parent Engagement', 'Play-Based Learning', 'Child Nutrition & Safety',
  ],
  'Translation, Language & Localisation': [
    'Translation (Afrikaans/English)', 'Translation (Other Languages)', 'Interpreting',
    'Sign Language Interpreting', 'Proofreading & Copy Editing', 'Subtitling & Captioning',
    'Transcription', 'Software & Website Localisation', 'Technical & Legal Translation',
    'Language Teaching', 'Terminology & Linguistics',
  ],
  'Between roles': [
    'Career Transition', 'Open to Opportunities', 'Upskilling & Study',
    'Freelance/Contract Work', 'Industry Knowledge & Networks',
  ],
  'Homemaker & Caregiver': [
    'Household & Family Management', 'Caregiving & Elder Care', 'Budgeting & Household Finance',
    'Volunteering & School Involvement', 'Event & Community Organising', 'Home Education',
  ],
  'Retired': [
    'Mentoring & Coaching', 'Board & Advisory Roles', 'Community Volunteering',
    'Consulting (Semi-Retired)', 'Industry Knowledge & Networks',
  ],
  'Student': [
    'Internships & Vacation Work', 'Academic Research', 'Student Leadership',
    'Part-Time/Freelance Work', 'Career Exploration',
  ],
}

// Consolidated: Services & Opportunities (merged Services + Collaboration)
export const SERVICES_OFFERED = [
  'Consulting',
  'Technical Expertise',
  'Job Opportunities',
  'Investment/Funding',
  'B2B Partnerships',
  'Client Referrals',
  'Supplier Introductions',
  'Market Insights',
  'Network Connections',
]

// Kept for backward compatibility but no longer shown in UI
export const COLLABORATION_TYPES = [
  'B2B Partnerships',
  'Joint Ventures',
  'Mentorship',
  'Investor Connections',
  'Supplier Relationships',
  'Client Referrals',
  'Knowledge Sharing',
  'Recruitment',
]

// New: Availability/Capacity
export const AVAILABILITY_OPTIONS = [
  'Available now',
  'Part-time available',
  'By request/ad-hoc',
  'Fully booked',
]

// New: Geographic focus
export const GEOGRAPHIC_FOCUS = [
  'Local (South Africa)',
  'Pan-Africa',
  'Global',
  'Remote only',
]

// SACS Alumni Association membership fields (profile_details table,
// schema-update: add_sacs_profile_details) — kept out of the core
// EXPERTISE/INDUSTRY-style lists above because these describe the person's
// membership record, not their profile-in-the-directory.
export const TITLES = ['Mr', 'Mrs', 'Ms', 'Miss', 'Dr', 'Prof', 'Rev', 'Adv', 'Other']

// SACS is a boys' school, so "Male" is the sensible default for a new
// member filling this in for the first time — but it's a plain dropdown,
// not a locked value, since staff members (who can also hold accounts here)
// aren't all men. See the default-to-Male logic in Profile.jsx.
export const GENDERS = ['Male', 'Female', 'Other', 'Prefer not to say']
